//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ImportEntities : DbContext
    {
        public ImportEntities()
            : base("name=ImportEntities")
        {
            this.Database.CommandTimeout = 420;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pannebakker> Pannebakkers { get; set; }
        public virtual DbSet<rawImport> rawImports { get; set; }
        public virtual DbSet<PlantName> PlantNames { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<PlantGroup> PlantGroups { get; set; }
    
        public virtual int sp_importmerge()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_importmerge");
        }
    
        public virtual int sp_removeimportduplicates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_removeimportduplicates");
        }
    
        public virtual int sp_removepannebakkerduplicates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_removepannebakkerduplicates");
        }
    
        public virtual int sp_removedupnames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_removedupnames");
        }
    
        public virtual int sp_mergenames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mergenames");
        }
    
        public virtual int sp_MergePBintoBatch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MergePBintoBatch");
        }
    
        public virtual int removeBatchDuplicates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("removeBatchDuplicates");
        }
    
        public virtual int sp_cleanFormSize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cleanFormSize");
        }
    
        public virtual int sp_cleanPB_FormSize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cleanPB_FormSize");
        }
    
        public virtual int sp_DeletePBFromBatch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePBFromBatch");
        }
    
        public virtual int UpdateActiveBatch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateActiveBatch");
        }
    }
}
