//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ImportEntities : DbContext
    {
        public ImportEntities()
            : base("name=ImportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pannebakker> Pannebakkers { get; set; }
        public virtual DbSet<rawImport> rawImports { get; set; }
    
        public virtual int sp_importmerge()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_importmerge");
        }
    
        public virtual int sp_removeimportduplicates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_removeimportduplicates");
        }
    
        public virtual int sp_removepannebakkerduplicates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_removepannebakkerduplicates");
        }
    }
}
