//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pannebakker
    {
        public int Id { get; set; }
        public string Sku { get; set; }
        public string FormSizeCode { get; set; }
        public string Name { get; set; }
        public string FormSize { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> RootBall { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string Location { get; set; }
        public Nullable<int> WholesalePrice { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
    }
}
