//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quoteService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrossProfitMargin
    {
        public int gpmId { get; set; }
        public decimal gpmValue { get; set; }
        public decimal rowMin { get; set; }
        public decimal rowMax { get; set; }
        public int gpmRuleset { get; set; }
    }
}
