//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quoteService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.PlantsForQuotes = new HashSet<PlantsForQuote>();
        }
    
        public int QuoteId { get; set; }
        public string CustomerReference { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public string SiteReference { get; set; }
        public Nullable<int> QuotePrice { get; set; }
        public Nullable<System.DateTime> QuoteExpiryDate { get; set; }
        public bool Active { get; set; }
        public bool SalesOrder { get; set; }
        public bool Retail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantsForQuote> PlantsForQuotes { get; set; }
    }
}
